# ===========================
# Stage 1 : Build
# ===========================
FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /workspace

COPY . .

RUN mvn clean package \
    -pl services/discovery-service \
    -am \
    -DskipTests

# ===========================
# Stage 2 : Runtime
# ===========================
FROM eclipse-temurin:21-jre

LABEL maintainer="Vaishnavi K"
LABEL application="FinVerse AI"
LABEL service="Discovery Service"

WORKDIR /app

COPY --from=builder /workspace/services/discovery-service/target/discovery-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8761

ENTRYPOINT ["java","-jar","app.jar"]
