spring:
    application:
        name: discovery-service

server:
    port: 8761

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false

    server:
        enable-self-preservation: true

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics

    endpoint:
        health:
            show-details: always

springdoc:
    swagger-ui:
      path: /swagger-ui.html
      display-request-duration: true
      operations-sorter: method

    api-docs:
      path: /api-docs

    packages-to-scan: com.finverse.discovery


    paths-to-match: /**


